### ISSUE TITLE
init.el

### ISSUE THREAD

**Issue by zhumingpassional** [zilongshanren/emacs.d#4]
看了你的视频，能否将init.el的内容贴出来啊？一个个字母敲很麻烦。并且自己敲的容易出错，发现打开emacs后Init.el不能自动执行

谢谢

**Comment by zilongshanren** [comment]
https://gitee.com/emacs-china/emacs.d 我传到了 gitee上面，后面会在 book.emacs-china.org 上面更新下

**Comment by zhumingpassional** [comment]
谢谢 希望楼主持续更新

如果能将最终版本的 inite.el更新在网上，就太棒了。期待大神

Wish you all my best.
Sincerely,
Ming Zhu.


子龙山人 ***@***.***> 于2022年5月18日周三 08:49写道：

**Comment by zilongshanren** [comment]
@zhumingpassional 订阅+小铃铛，我会尽量保持更新频率的
